### ISSUE TITLE
Add "id" to access more than one shinyalert in a App

### ISSUE THREAD

**Issue by gsrnivas** [daattali/shinyalert#11]
I am using shinyalrert more than once and I would prefer to use id's to refer to different alerts. The second one overwrites the first one and there is no chance to get both without storing them to a reactive value variable. It would be great if you considering adding this. Thank you.

**Comment by daattali** [comment]
That makes sense. You could also use the `callbackR` parameter to get the value instead of using `input$shinyalert`. I actually prefer using callbacks in this case because with the input version, there are problems you can come across. If two consecutive modals have the exact same value, then the second one won't trigger the input value since it hasn't changed (similar to [this issue](https://github.com/rstudio/shiny/issues/928)). But I can look into potentially adding an extra parameter where you can specify the name of the input, where `shinyalert` is the default

**Comment by daattali** [comment]
@gsrnivas I've implemented this feature, using a new `inputId` parameter. Please try it out and let me know if that's what you had in mind!
