### ISSUE TITLE
Replace free text by closed input

### ISSUE THREAD

**Issue by jlopezper** [daattali/shinyalert#40]
Thanks for this fantastic package.

I'm using `shinyalert` right now to collect feedback from users and store that information for analysis purposes. Now I'd like to change the free text mode to a closed input (something like radio buttons). In the documentation of the `shinyalert` function I see that in the `inputType` argument another valid HTML input can be specified. When I set this argument to "radio" it doesn't take up the text I specify in the `inputValue` argument:

![image](https://user-images.githubusercontent.com/20323137/93578718-f3948500-f99d-11ea-9603-93d2e3b3ce8e.png)

Is this possible in `shinyalert` or is there a workaround?

Thanks in advance.

**Comment by jlopezper** [comment]
I think radio buttons are technically a [html input tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio).

**Comment by daattali** [comment]
Yes you're right. I was thinking about select inpiut dropdowns.

So technically a radio button would work, but wouldn't be very useful since it'll just show a single radio button, and radio buttons are only useful when you have multiple. Any of the [input types](https://www.w3schools.com/html/html_form_input_types.asp) that make sense as a single input would make sense in a shinyalert.

If you want radio buttons (or anything else that's beyond a simple single input) you can now do that since shinyalert now accepts any shiny UI, as the new documentation says.

**Comment by jlopezper** [comment]
Yes, perhaps this could be sorted out by allowing `inputValue` to be a character vector when `inputType` is set to be a radio button or checkbox, for example. In any case, I don't know what technical complexity this change would entail.

Thank you for your response. I will take a look at the latest version.

**Comment by daattali** [comment]
I don't think the underlying sweetalert javascript library would support a vector being passed in. As per their documentation, they simply say that inputType can be any input and inputValue will be the default value of the input (not the text beside the input, which makes me believe they don't explicitly support radio/checkboxes). In either case, I 100% recommend updating to v2.0 (just take note of the slight breaking changes in NEWS.md)
