### ISSUE TITLE
action button not popping off/showing in shinyapp

### ISSUE THREAD

**Issue by raeyu1** [daattali/shinyalert#63]
Does anyone know how to fix my problem here? It's just my action button is not showing, I am also not sure if I can input some matrix if it shows.

library(shiny)
library(shinythemes)
library(shinydashboard)
library(shinyMatrix)

ui <- fluidPage(
  
  navbarPage(title = "DETERMINANTS CALCULATOR",
             theme = shinytheme("sandstone"),
             tabPanel(value = "Home", icon("home"),
                      fluidRow(column(width=12,height=20,
                                      
               tags$h1("Determinants", height = 4, style = "font-weight: bold; text-align; center;"),
               mainPanel(width = 3, height = 8, style = "border-style: solid; border-color: black;",
               br(),
               selectInput("matrix", "Choose a matrix dimension:", c("2", "3"),
               actionButton("set", "Set as Matrix"),
               ),
               ),
               ),
                mainPanel(
                  uiOutput("matrixInput"),
                  br(),
                  actionButton("calculate", "Calculate"),
                  tags$h3("Result of the Matrix", style = "font-weight: bold; text-align;center;"),
          )
          )               
          ),
             tabPanel(value = "About", icon("address-card"),
                      sidebarPanel(
                        h2("About the App", style = "font-weight: bold;"),
                        p("This web application complies with the final project or learning evidence to CS111, Advance Algebra for the first semester. This application can solve a 2x2 and 3x3 determinant matrix and multiply to row from echelon form to its diagonal element.", style = "font-weight:bold; text-center;")
      )
    )
  )  
)

# Sever matrix
server <- function(input, output) 
  valueofdet = eventReactive(input$set, {
    matrix(
      nrow = input$matrix,
      ncol = input$matrix
    )
  })
# Run the application 
shinyApp(ui = ui, server = server)

**Comment by daattali** [comment]
Hi @raeyu1 

If you believe there's a bug in shinyalert, please file an issue with a [**minimal reprex**](https://community.rstudio.com/t/faq-how-to-do-a-minimal-reproducible-example-reprex-for-beginners/23061) and make sure to [format your message](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) so that it's legible.

If you're asking for personal help with the package, this is not the place for that - this is only for reporting issues.

I'm closing this issue for now as it's not clear whether there's a problem with shinyalert or if you're just asking for help.
