### ISSUE TITLE
R 4.2.0: warning in if-condition when using multiline HTML text

### ISSUE THREAD

**Issue by lgaborini** [daattali/shinyalert#68]
Simple reprex:

```r
library(shiny)
library(shinyalert)

ui <- fluidPage(
   actionButton("preview", "Preview")
)

server <- function(input, output, session) {
   observeEvent(input$preview, {
      
      # Show a modal when the button is pressed
      shinyalert(
         title = "Test",
         html = TRUE,
         text = c(
            "Line1",
            "Line2"
         )
      )
      
   })
}

shinyApp(ui, server)
```

The warning is:
> Warning in html && nzchar(params[["text"]]) :
  'length(x) = 2 > 1' in coercion to 'logical(1)'

**Comment by daattali** [comment]
@lgaborini thanks for the report. Can you please install latest version and confirm you don't see the warning

**Comment by lgaborini** [comment]
Confirm fixed!

**Comment by BajczA475** [comment]
I am still getting this warning running version 3.0.0 of this package which looks to be the latest version on CRAN. It looks like this warning has transitioned or will soon be transitioning to an error (https://stackoverflow.com/questions/72848442/r-warning-lengthx-2-1-in-coercion-to-logical1), which is why I'm writing this here--I'm now getting an error in my shiny app upon clicking the button that triggers my shiny alerts when I wasn't before, and I think it's faulting this chunk in the shinyalert.R script:

if (html && !is.null(params[["text"]]) && (length(params[["text"]]) > 1 || nzchar(as.character(params[["text"]])))) {
    if (type == "input") {
      stop("Cannot use 'input' type and HTML together. You must supply your own Shiny inputs when using HTML.", call. = FALSE)
    }

It looks like how && and || work has shifted in recent updates of R and may now be breaking some previously working code? I see those operators in a few other lines in here also...

Using the reprex in this Thread, I still get a warning, not an error, FWIW.

**Comment by daattali** [comment]
Please install the latest **dev/GitHub** version, the fix is not on CRAN yet

**Comment by daattali** [comment]
A new version was submitted to CRAN today, it will be on CRAN in a few days
